# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.yigitozen.com/
title: Yiğit Özen
author: Yiğit Özen
description: yigitozendotcom
avatar: profile.jpg
email: ygtozen@gmail.com
github: yigitozen # username
twitter: ozenyigit
linkedin: ozenyigit
instagram: ozenyigit   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-96291904-1


# needed for travis-ci build
exclude: [vendor]
